### PR TITLE
Leaderboard versions

### PR DESCRIPTION
**Pull request by zomglings**
This pull request introduces the notion of leaderboard versions.

Resolves https://github.com/moonstream-to/api/issues/954

#### List versions

`GET /leaderboard/<leaderboard_id>/versions`

Lists all versions of the leaderboard with the given ID that the caller can view 

If authenticated and has read access to leaderboard resource, then the caller can view all versions -- published and not published, otherwise only the published versions.

#### Get version

`GET /leaderboard/<leaderboard_id>/versions/<version_number>`

Shows information about the given version of the given leaderboard.

If the user calls without an access token or provides an access token for a user who doesn't have access to the leaderboard resource, then this endpoint only returns version information for published versions. Otherwise it returns a 404 response.

#### Create new version

`POST /leaderboard/<leaderboard_id>/versions`

Create a new version of the leaderboard with the given ID.

Caller must provide access token of account that has access to the leaderboard resource.

#### Update existing version

`PUT /leaderboard/<leaderboard_id>/versions/<version_number>`

This can publish/unpublish a leaderboard version.

Caller must provide access token of account that has access to the leaderboard resource.

### Changes to existing endpoints

All existing GET endpoints take a `?version=<version_number>` query parameter.

If provided, assuming the version is public and request is not authorized, it restricts the query to that version. If version is not public and request is not authorized, 404 response. If version is not public and response is authorized, then it shows data for that version. If provided version doesn't exist, 404.

If not provided, it looks up the highest public version and run the query over that version. If there is no public version, it returns an empty response (e.g. empty array).

### CODE REVIEW

**Review by kompotkot — APPROVED** [review]
lg

**Comment by Andrei-Dolgolev** [comment]
```markdown
# Leaderboard API Endpoints Documentation

## Authorized Endpoints

### GET Leaderboards

```http
GET http://127.0.0.1:7191/leaderboard/leaderboards
Authorization: Bearer <token>
```

### Create Leaderboard

```http
POST http://127.0.0.1:7191/leaderboard/
Authorization: Bearer <token>

{
  "title": "Test columnnames",
  "description": "Encoded description here...",
  "columns_names": {
    "address": "token_id"
  }
}
```

### Get Scores (If Not Found and Public is False)

```http
GET http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>
```

### Update Leaderboard (Make Public)

```http
PUT http://127.0.0.1:7191/leaderboard/<leaderboard_id>
Authorization: Bearer <token>
Content-Type: application/json

{
  "public": true
}
```

### Get Leaderboard Scores

```http
GET http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>
```

### Get Leaderboard Info

```http
GET http://127.0.0.1:7191/leaderboard/info?leaderboard_id=<leaderboard_id>&version=1
```

### Push Scores to Leaderboard

```http
PUT http://127.0.0.1:7191/leaderboard/<leaderboard_id>/scores?overwrite=true
Authorization: Bearer <token>
Content-Type: application/json

[{
  "address": "0x0000000000000000000000000000000000000000",
  "score": 200000000,
  "points_data": {
    "breeding": 100000000,
    "hatchingEggs": 100000000
  }
}]
```

### Count Addresses in Leaderboard

```http
GET http://127.0.0.1:7191/leaderboard/count/addresses?leaderboard_id=<leaderboard_id>&version=0
```

### Get Quartiles of Leaderboard

```http
GET http://127.0.0.1:7191/leaderboard/quartiles?leaderboard_id=<leaderboard_id>&version=0
```

### Get Leaderboard Position

```http
GET http://127.0.0.1:7191/leaderboard/position?leaderboard_id=<leaderboard_id>&address=1232&version=2&normalize_addresses=false&window_size=1
```

### Get Leaderboard Rank

```http
GET http://127.0.0.1:7191/leaderboard/rank?leaderboard_id=<leaderboard_id>&rank=2&version=0
```

### Get Leaderboard Ranks

```http
GET http://127.0.0.1:7191/leaderboard/ranks?leaderboard_id=<leaderboard_id>&version=2
```

### Get Leaderboard Scores by Version

```http
GET http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/0/scores
Authorization: Bearer <token>
Content-Type: application/json
```

### Get Leaderboard Versions

```http
GET http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions
Authorization: Bearer <token>
Content-Type: application/json
```

### Update Leaderboard Version (Publish)

```http
PUT http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/0
Authorization: Bearer <token>
Content-Type: application/json

{
  "publish": true
}
```

### Delete Leaderboard Version

```http
DELETE http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/2
Authorization: Bearer <token>
Content-Type: application/json
```

### Update Scores for Specific Leaderboard Version

```http
PUT http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/1/scores?normalize_addresses=false&overwrite=true
Authorization: Bearer <token>
Content-Type: application/json

[{
  "address": "0x000000000000000000000000000000000000000q",
  "score": 2000000,
  "points_data": {
    "breeding": 100000000,
    "hatchingEggs": 100000000
  }
}]
```

### Get Scores for Specific Leaderboard Version

```http
GET http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>&version=5
```

### Create New Version for Leaderboard

```http
POST http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions
Authorization: Bearer <token>
Content-Type: application/json

{
  "publish": false
}
```

**Comment by Andrei-Dolgolev** [comment]
```markdown
# Leaderboard API Endpoints Documentation

## Authorized Endpoints

### GET Leaderboards

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/leaderboards" -H "Authorization: Bearer <token>"
```

### Create Leaderboard

```bash
curl -X POST "http://127.0.0.1:7191/leaderboard/" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
  "title": "Test columnnames",
  "description": "description here..."
}'
```

### Get Scores (If Not Found and Public is False)

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>"
```

### Get Leaderboard Scores

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>&version=1"
```

### Get Leaderboard Info

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/info?leaderboard_id=<leaderboard_id>&version=1"
```

### Push Scores to Leaderboard

```bash
curl -X PUT "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/scores?overwrite=true" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
  "address": "0x0000000000000000000000000000000000000000",
  "score": 200000000,
  "points_data": {
    "breeding": 100000000,
    "hatchingEggs": 100000000
  }
}'
```

### Count Addresses in Leaderboard

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/count/addresses?leaderboard_id=<leaderboard_id>&version=0"
```

### Get Quartiles of Leaderboard

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/quartiles?leaderboard_id=<leaderboard_id>&version=0"
```

### Get Leaderboard Position

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/position?leaderboard_id=<leaderboard_id>&address=1232&version=2&normalize_addresses=false&window_size=1"
```

### Get Leaderboard Rank

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/rank?leaderboard_id=<leaderboard_id>&rank=2&version=0"
```

### Get Leaderboard Ranks

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/ranks?leaderboard_id=<leaderboard_id>&version=2"
```

### Get Leaderboard Scores by Version

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/0/scores" -H "Authorization: Bearer <token>"
```

### Get Leaderboard Versions

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions" -H "Authorization: Bearer <token>"
```

### Update Leaderboard Version (Publish)

```bash
curl -X PUT "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/0" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
  "publish": true
}'
```

### Delete Leaderboard Version

```bash
curl -X DELETE "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/2" -H "Authorization: Bearer <token>"
```

### Update Scores for Specific Leaderboard Version

```bash
curl -X PUT "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions/1/scores?normalize_addresses=false&overwrite=true" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
  "address": "0x000000000000000000000000000000000000000q",
  "score": 2000000,
  "points_data": {
    "breeding": 

100000000,
    "hatchingEggs": 100000000
  }
}'
```

### Get Scores for Specific Leaderboard Version

```bash
curl -X GET "http://127.0.0.1:7191/leaderboard/?leaderboard_id=<leaderboard_id>&version=5"
```

### Create New Version for Leaderboard

```bash
curl -X POST "http://127.0.0.1:7191/leaderboard/<leaderboard_id>/versions" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
  "publish": false
}'
```
```

**Comment by Andrei-Dolgolev** [comment]
After adding versions current downgrade script will not work because of possible `UniqueViolation` in
`ADD CONSTRAINT uq_leaderboard_scores_leaderboard_id UNIQUE (leaderboard_id, address)]`.

**Comment by zomglings** [comment]
> After adding versions current downgrade script will not work because of possible `UniqueViolation` in `ADD CONSTRAINT uq_leaderboard_scores_leaderboard_id UNIQUE (leaderboard_id, address)]`.

Fixed this issue with downgrade.

**Review by Andrei-Dolgolev — APPROVED** [review]
lgtm

**Pull request merged**
